// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyhrwjimscvotbazvxol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5aHJ3amltc2N2b3RiYXp2eG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDA1OTYsImV4cCI6MjA3NDI3NjU5Nn0.wp2bdZD9T5vl1wZd146GD8L_MAwwis0ZcV7Irqn3Fyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});